name: Publish to Dockerhub
on:
    workflow_dispatch: {}
jobs:
  publish-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
            version: '8'
            architecture: x64
      - name: Apicurito Checkout
        run: |
          mkdir apicurito
          cd apicurito
          git init
          git remote add origin "https://github.com/colvinco/apicurito.git"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
      - name: Build Apicurito
        run: |
          sudo apt-get update
          sudo apt-get install --reinstall ca-certificates
          cd apicurito
          mvn clean install -D::image
